In [40]:
import pandas as pd 
import numpy as np

In [41]:
#df = pd.read_csv('documentos/resultados/redenciones_fs.csv', sep=';')
#df_resultados = pd.read_csv('documentos/resultados/redenciones_fs.csv', sep=';', encoding='ISO-8859-1')

df = pd.read_excel('documentos/redenciones/cp_redenciones.xlsx', sheet_name='Casos de Prueba')

In [42]:
df.head(30)

,Casos de Prueba,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Proyecto:,Redencion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ciclo de Pruebas:,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ID,Caso de Prueba,Descripción,Fecha,Área Funcional / Sub proceso,Funcionalidad / Característica,Datos / Acciones de Entrada,Resultado Esperado,Requerimientos de Ambiente de Pruebas,Procedimientos especiales requeridos,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Estatus,Estatus
5,1,Redencion Mantenedor -Exitoso,Se ingresa al mantenedor con el usuario NBA en...,2023-11-03 00:00:00,Redencion,Redencion Mantenedor,* Usuario NBA\n*Crear bloque\n*Agregar categor...,"Se crea bloque, categoria y beneficio con éxito.",Usuario NBA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Critico,Desarrollo
6,2,Redencion Mantenedor reportes -Exitoso,Se ingresa al mantenedor con el usuario NBA en...,2023-11-03 00:00:00,Redencion,Redencion Mantenedor reportes,* Usuario NBA\n* Generar Reporte.\n,Geracion de reporte exitoso,Usuario NBA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alto,Progreso
7,3,Redencion APP - Exitoso,Se ingresa a la aplicacon con el DN 5537685200...,2023-11-03 00:00:00,Redencion,Redencion APP,* DN apto para redencio.\n*Menu Hambuerguesa.\...,Flujo de redecnion exitoso,*DN apto para Redencion,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bajo,Incidencia
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finalizada
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,Migraciones OTC,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
subset = df.iloc[5:8]
subset1 = subset[['Unnamed: 2', 'Unnamed: 7']]
# Supongamos que df es tu DataFrame y que quieres cambiar el nombre de 'Unnamed: 2' a 'nuevo_nombre1' y 'Unnamed: 7' a 'nuevo_nombre2'

,Unnamed: 2,Unnamed: 7
5,Se ingresa al mantenedor con el usuario NBA en...,"Se crea bloque, categoria y beneficio con éxito."
6,Se ingresa al mantenedor con el usuario NBA en...,Geracion de reporte exitoso
7,Se ingresa a la aplicacon con el DN 5537685200...,Flujo de redecnion exitoso

In [44]:
subset2 = subset1.rename(columns={'Unnamed: 2': 'caso de prueba', 'Unnamed: 7': 'resultado esperado'})
subset2

,caso de prueba,resultado esperado
5,Se ingresa al mantenedor con el usuario NBA en...,"Se crea bloque, categoria y beneficio con éxito."
6,Se ingresa al mantenedor con el usuario NBA en...,Geracion de reporte exitoso
7,Se ingresa a la aplicacon con el DN 5537685200...,Flujo de redecnion exitoso

In [56]:
subset2.to_csv('casos_de_prueba.csv', index=False)

In [9]:
import libs.check_encoding

check_encoding.check_encoding('documentos/redenciones/cp_redenciones.xlsx')

NameError: name 'check_encoding' is not defined

In [5]:
import convert_excel_to_csv

convert_excel_to_csv.convert_excel_to_csv('documentos/redenciones/cp_redenciones.xlsx', 'documentos/redenciones/cp_redenciones.csv')

ModuleNotFoundError: No module named 'convert_excel_to_csv'